"""follow up model

Revision ID: 3ee97219e611
Revises: d57f4c084792
Create Date: 2024-12-06 01:58:40.456172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ee97219e611'
down_revision: Union[str, None] = 'd57f4c084792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up_reports',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['report_uid'], ['reports.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.add_column('reports', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'is_active')
    op.drop_table('follow_up_reports')
    # ### end Alembic commands ###
