"""reworked tables

Revision ID: 5c29814a9c01
Revises: b352ea642991
Create Date: 2024-12-09 09:24:06.536139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c29814a9c01'
down_revision: Union[str, None] = 'b352ea642991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agencies', 'agency_type')
    op.drop_column('agencies', 'address')
    op.add_column('reports', sa.Column('progress', postgresql.ENUM('Submitted', 'InProcessing', 'Resolved', name='report_progress'), nullable=False))
    op.drop_constraint('reports_user_uid_fkey', 'reports', type_='foreignkey')
    op.drop_column('reports', 'user_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('user_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('reports_user_uid_fkey', 'reports', 'users', ['user_uid'], ['uid'])
    op.drop_column('reports', 'progress')
    op.add_column('agencies', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('agencies', sa.Column('agency_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
